watch-inspectsimpler:
	spago bundle-app --main InspectSimpler --watch --clear-screen --to inspectsimpler.js-purescript --then "./postprocess.sh inspectsimpler.js"

build-velocity:
	spago bundle-app --main Velocity --to velocity.js-purescript
	./postprocess.sh velocity.js

watch-velocity:
	spago bundle-app --main Velocity --watch --clear-screen --to velocity.js-purescript --then "./postprocess.sh velocity.js"

